# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs: 
  deploy_build:
    docker: 
      - image: cimg/base:2020.01
    steps:    
      - checkout    
      - run: ssh -oStrictHostKeyChecking=no -v $DROPLET_USER@$DROPLET_IP "sh ./deploy_script.sh"
workflows:  
  version: 2  
  deploy_build:
    jobs:
      - deploy_build